### ISSUE TITLE
Add python 3.5

### ISSUE THREAD

**Issue by rageshkrishna** [dry-dock/u14pytpls#5]

**Comment by balavignesh-s** [comment]
build fails with python3.5. With python3.5, apparently there is a change in the format of the system version information. As a result there is an assertion error in wheel package. They have fixed this issue in wheels
https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3
 But we are not using the version of wheels which incorporates the above fix. Hence we get the assertion error and build fails. Though the build throws error, image is successfully built and the docker image can be successfully run.

Apart from this, a lot of other test cases fails when building this image which we will have to look into.

Edit: Solved by running pip install --upgrade wheel
